---
- name: "install httpd software"
  package: 
      name: "httpd"
      state: present

- name: "configure httpd service"
  copy:
      src: "index.html"
      dest: "/var/www/html"
  register: config

- name: "start web service"
  command:
      cmd: "/usr/sbin/httpd"
  when: config.changed == true
  
